### ISSUE TITLE
Error: PublishError.NoPeersSubscribedToTopic on put document

### ISSUE THREAD

**Issue by fenicento** [orbitdb/quickstart#5]
Hi, 
I'm using the quickstart configuration from browser. When I try to put a document in a "documents" db I receive the following error:

@orbitdb_quickstart.js?v=d54e0f91:99281 Uncaught (in promise) Error: PublishError.NoPeersSubscribedToTopic
    at GossipSub2.publish (@orbitdb_quickstart.…v=d54e0f91:99281:13)
    at async Object.add2 [as add] (@orbitdb_quickstart.…?v=d54e0f91:90463:7)
    at async task (@orbitdb_quickstart.…?v=d54e0f91:91401:7)
    at async @orbitdb_quickstart.…v=d54e0f91:32457:26

I guess there's something wrong in the default libp2p configuration. Is this possibly related to https://github.com/orbitdb/orbitdb/issues/1172?

**Comment by haydenyoung** [comment]
Correct.  `allowPublishToZeroTopicPeers: true` appears to be the correct configuration for newer versions of Libp2p.

**Comment by haydenyoung** [comment]
Closing this issue as there has been no update. If the issue persists, please feel free to re-open and provide additional information about the problem you are experiencing. If you have successfully fixed the issue, PRs are always welcome.
